language: objective-c
os:
  - osx
before_install:
  - sudo xcodebuild -license
  - xcode-select --install
  - ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  - brew doctor
  - brew update
  - brew install python
  - brew install ansible
  - make playbook
script: 
  - make test
