language: objective-c
services:
  - docker
os:
  - osx
before_install:
  - brew update
  - brew install python
  - brew install ansible
  - ansible-playbook -vvvvv playbook.yml -i hosts
script: 
  - make test
