- name: Install homebrew
  command: ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" creates=/usr/local/bin/brew

- name: Setup homebrew cask
  homebrew_tap: tap={{ item.tap }} state={{ item.state }}
  with_items:
      - {tap: "caskroom/cask", state: "present"}

- name: Install homebrew cask
  homebrew: name=cask state=present

- name: Update homebrew
  homebrew: update_homebrew={{ homebrew_update }} upgrade_all={{ homebrew_upgrade_all }}

- name: Upgrade homebrew cask
  homebrew: name=cask state=latest
  when: homebrew_update == "yes"

- name: Cleanup homebrew
  shell: brew cleanup && brew cask cleanup
  when: homebrew_update == "yes"

- name: Install basic packages
  homebrew: name={{ item.name }} state={{ item.state }}
  with_items:
      - {name: "autoconf", state: "present"}
      - {name: "cask", state: "present"}
      - {name: "git", state: "present"}
      - {name: "hub", state: "present"}
      - {name: "git-flow", state: "present"}
      - {name: "libyaml", state: "present"}
      - {name: "mycli", state: "present"}
      - {name: "cscope", state: "present"}
      - {name: "ctags", state: "present"}
      - {name: "gdbm", state: "present"}
      - {name: "pcre", state: "present"}
      - {name: "mackup", state: "present"}
      - {name: "nmap", state: "present"}
      - {name: "gibo", state: "present"}
      - {name: "readline", state: "present"}
      - {name: "the_silver_searcher", state: "present"}
      - {name: "tig", state: "present"}
      - {name: "tmux", state: "present"}
      - {name: "peco", state: "present"}
      - {name: "nvm", state: "present"}
      - {name: "ruby-build", state: "present"}
      - {name: "rbenv", state: "present"}
      - {name: "rbenv-default-gems", state: "present"}
      - {name: "gnu-tar", state: "present"}
      - {name: "ack", state: "present"}
      - {name: "findutils", state: "present"}
      - {name: "readline", state: "present"}
      - {name: "openssl", state: "present"}
      - {name: "gdbm", state: "present"}
      - {name: "sqlite", state: "present"}
      - {name: "vim", state: "present"}
      - {name: "zsh", state: "present"}
      - {name: "zsh-completions", state: "present"}
      - {name: "zsh-syntax-highlighting", state: "present"}

